OBSERVATIONS = "observations"
ACTIONS = "actions"
HIDDEN_STATES = "hidden_states"
REWARDS = "rewards"
DONES = "dones"
TERMINATEDS = "terminateds"
TRUNCATEDS = "truncateds"
INFOS = "infos"
NEXT_OBSERVATIONS = "next_observations"
NEXT_HIDDEN_STATES = "next_hidden_states"
LAST_OBSERVATIONS = "last_observations"
LAST_HIDDEN_STATES = "last_hidden_states"

AGENT = "agent"
LEARNER = "learner"
LEARNERS = "learners"
OFFLINE = "offline"
ONLINE = "online"
PRETRAIN = "pretrain"

BUFFER_SIZE = "buffer_size"
POINTER = "pointer"
COUNT = "count"
DTYPE = "dtype"
RNG = "rng"
BURN_IN_WINDOW = "burn_in_window"

CURR_EPISODE_LENGTH = "curr_episode_length"
EPISODE = "episode"
EPISODE_IDXES = "episode_idxes"
EPISODE_LENGTH = "episode_length"
EPISODE_LENGTHS = "episode_lengths"
EPISODE_START_IDXES = "episode_start_idxes"
EPISODIC_RETURN = "episodic_return"
TIMEDIFF = "time_diff"
TIMESTEP = "timestep"
STEP = "step"

RESET = "reset"

CONTINUOUS = "continuous"
DISCRETE = "discrete"

NORMALIZE_OBS = "normalize_obs"
NORMALIZE_VALUE = "normalize_value"

EXPLORATION_STEPS = "exploration_steps"
EXPLORATION_STRATEGY = "exploration_strategy"
RANDOM_EXPLORATION = "random_exploration"

CLIP_ACTION = "clip_action"

UNIFORM_CATEGORICAL = "uniform_categorical"
STANDARD_GAUSSIAN = "standard_gaussian"
